<template>
  <main class="min-h-screen bg-[#f5f7fb] p-4 md:p-6"><div class="mx-auto grid max-w-4xl gap-6 md:grid-cols-4">
    <aside class="md:col-span-1"><section class="rounded-lg border border-slate-200 bg-white p-4 shadow-sm"><div class="mb-4 flex items-center gap-2"><el-avatar :size="36" class="bg-blue-100 font-bold text-blue-600">{{ candidateInitial }}</el-avatar><div class="min-w-0 flex-1"><div class="truncate text-sm font-semibold text-slate-900">{{ candidateName || '候选人' }}</div><div class="truncate text-xs text-slate-500">{{ candidateEmail }}</div></div><el-tooltip content="退出登录"><el-button circle size="small" @click="logout"><el-icon><SwitchButton /></el-icon></el-button></el-tooltip></div><div class="border-t border-slate-100 pt-3"><div class="mb-2 text-xs font-semibold uppercase tracking-wider text-slate-400">我的投递</div><div class="space-y-1"><button v-for="application in applications" :key="application.candidate_id" :class="['w-full rounded-lg border p-2.5 text-left text-xs transition', selectedId === application.candidate_id ? 'border-blue-200 bg-blue-50 font-semibold text-blue-700' : 'border-transparent text-slate-600 hover:bg-slate-50']" @click="selectApplication(application.candidate_id)"><div class="mb-1 flex items-center justify-between gap-1"><span class="truncate">{{ application.position_title }}</span><el-tag size="small" :type="statusTag(application.status)">{{ application.status }}</el-tag></div><div class="text-[10px] font-normal text-slate-400">投递时间：{{ formatTime(application.applied_at) }}</div></button></div></div></section></aside>
    <section class="flex h-[600px] flex-col overflow-hidden rounded-lg border border-slate-200 bg-white shadow-sm md:col-span-3"><template v-if="selected"><header class="flex items-center justify-between border-b border-slate-100 bg-white px-5 py-4"><div><h2 class="font-semibold text-slate-900">{{ selected.position_title }}</h2><p class="mt-1 text-xs text-slate-500">当前招聘进度：<el-tag size="small" :type="statusTag(selected.status)">{{ selected.status }}</el-tag></p></div><span class="text-xs text-slate-400">消息由负责 HR 人工处理</span></header><div ref="messageBox" class="flex-1 space-y-4 overflow-y-auto bg-slate-50/50 p-5"><div v-for="message in messages" :key="message.id" class="flex" :class="message.sender_type === 'candidate' ? 'justify-end' : 'justify-start'"><div class="flex max-w-[85%] gap-2" :class="message.sender_type === 'candidate' ? 'flex-row-reverse' : ''"><el-avatar :size="32" :class="message.sender_type === 'candidate' ? 'bg-blue-600 text-white' : 'bg-slate-200 text-slate-700'">{{ message.sender_type === 'candidate' ? candidateInitial : 'HR' }}</el-avatar><div><div class="mb-1 text-[10px] text-slate-400" :class="message.sender_type === 'candidate' ? 'text-right' : ''">{{ message.sender_type === 'candidate' ? '我' : 'HR' }} · {{ formatTime(message.created_at) }}</div><div :class="['rounded-lg px-4 py-2.5 text-sm leading-relaxed shadow-sm whitespace-pre-wrap', message.sender_type === 'candidate' ? 'rounded-br-none bg-blue-600 text-white' : 'rounded-bl-none border border-slate-200 bg-white text-slate-800']">{{ message.content }}</div></div></div></div><el-empty v-if="!messages.length && !loading" description="向 HR 发起第一条消息吧" /></div><footer class="border-t border-slate-100 bg-white p-4"><div class="flex gap-2"><el-input v-model="draft" type="textarea" :rows="2" resize="none" placeholder="请输入您想咨询或回复的内容…" @keydown.ctrl.enter.prevent="send" /><el-button class="h-auto px-6" type="primary" :disabled="!draft.trim()" :loading="sending" @click="send">发送</el-button></div><div class="mt-2 flex justify-between text-[11px] text-slate-400"><span>按 Ctrl + Enter 快捷发送</span><span>沟通记录仅供招聘流程使用</span></div></footer></template><div v-else class="flex flex-1 flex-col items-center justify-center bg-slate-50/20 text-slate-400"><el-icon :size="48"><ChatDotSquare /></el-icon><p class="mt-2 text-sm">请在左侧选择一个职位投递进入会话</p></div></section>
  </div></main>
</template>

<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from 'vue'
import { ChatDotSquare, SwitchButton } from '@element-plus/icons-vue'
import { ElMessage } from 'element-plus'
import { useRouter } from 'vue-router'
import { candidatePortalTokenKey, getPortalApplications, getPortalMessages, sendPortalMessage, type PortalApplication, type PortalMessage } from '@/apis/candidate_portal_api'

const router = useRouter(); const applications = ref<PortalApplication[]>([]); const selectedId = ref(''); const messages = ref<PortalMessage[]>([]); const draft = ref(''); const loading = ref(false); const sending = ref(false); const messageBox = ref<HTMLElement>(); let pollTimer: number | undefined
const selected = computed(() => applications.value.find((item) => item.candidate_id === selectedId.value)); const candidateName = computed(() => selected.value?.candidate_name || applications.value[0]?.candidate_name || ''); const candidateEmail = computed(() => localStorage.getItem('candidatePortalEmail') || ''); const candidateInitial = computed(() => (candidateName.value || candidateEmail.value || '候').slice(0, 2).toUpperCase())
const formatTime = (value?: string | null) => value ? new Date(value).toLocaleString('zh-CN', { month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit' }) : '-'
const statusTag = (value: string) => value.includes('通过') || value.includes('入职') ? 'success' : value.includes('拒绝') || value.includes('未通过') ? 'danger' : 'info'
const scrollDown = async () => { await nextTick(); if (messageBox.value) messageBox.value.scrollTop = messageBox.value.scrollHeight }
const loadMessages = async (keepPosition = false) => { if (!selectedId.value) return; loading.value = true; try { messages.value = (await getPortalMessages(selectedId.value)).items; if (!keepPosition) await scrollDown() } catch (error: any) { if (error.response?.status === 401) logout(); else ElMessage.error('加载会话失败') } finally { loading.value = false } }
const selectApplication = (id: string) => { selectedId.value = id; void loadMessages() }
const send = async () => { if (!draft.value.trim() || !selectedId.value) return; sending.value = true; try { const result = await sendPortalMessage(selectedId.value, draft.value.trim()); messages.value.push(result.message); draft.value = ''; await scrollDown() } catch { ElMessage.error('发送失败，请稍后重试') } finally { sending.value = false } }
const logout = () => { localStorage.removeItem(candidatePortalTokenKey); localStorage.removeItem('candidatePortalEmail'); router.replace('/candidate-portal/login') }
onMounted(async () => { loading.value = true; try { applications.value = (await getPortalApplications()).items; if (applications.value[0]) { selectedId.value = applications.value[0].candidate_id; await loadMessages() } pollTimer = window.setInterval(() => { if (document.visibilityState === 'visible') void loadMessages(true) }, 15000) } catch (error: any) { if (error.response?.status === 401) logout(); else ElMessage.error('投递记录加载失败') } finally { loading.value = false } })
onBeforeUnmount(() => { if (pollTimer) window.clearInterval(pollTimer) })
</script>
